# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: No Hold Music
email: support@noholdmusic.org
description: > # this means to ignore newlines until "baseurl:"
  Open source replacement for Apple Help Manager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://noholdmusic.org" # the base hostname & protocol for your site
#twitter_username: noholdmusic
github_username:  noholdmusic

# Build settings
markdown: kramdown
