//
//  FloatBalloon.h
//  No Hold Music
//
//  Created by Mark Williams on 5/10/16.
//  Copyright (c) 2016 The Fascinating Group. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//
//  While this file is licensed under Apache 2.0, the original balloon image is
//  licensed under CC BY 3.0 US
//     http://creativecommons.org/licenses/by/3.0/us/
//  A copy of the image with appropriate licensing is available at
//     https://thenounproject.com/term/balloon/232963/


#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>


@interface NHMFloatBalloonImage : NSObject

// Drawing Methods
+ (void)drawBalloonWithBalloonFillColor: (NSColor*)balloonFillColor;
+ (void)drawAcknowledgement;

// Generated Images
+ (NSImage*)imageOfBalloonWithBalloonFillColor: (NSColor*)balloonFillColor;

@end
